### ISSUE TITLE
Add FFmpeg to container

### ISSUE THREAD

**Issue by the0ckid82** [PhasecoreX/docker-red-discordbot#20]
**Is your feature request related to a problem? Please describe.**
when using the sfx command from [baiumbg-cogs](https://github.com/baiumbg/baiumbg-Cogs) tts cog fails due to missing dependency of ffmpeg

**Describe the solution you'd like**
Container to include FFmpeg

**Describe alternatives you've considered**
currently installing ffmpeg once container is running but this does not work as a long term solution as it does not persist past rebuilding of the container 

**Additional context**
```Exception in command 'tts'
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/cogs/CogManager/cogs/sfx/sfx.py", line 65, in tts
    audio_data = pydub.AudioSegment.from_mp3(audio_file)
  File "/data/cogs/Downloader/lib/pydub/audio_segment.py", line 738, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "/data/cogs/Downloader/lib/pydub/audio_segment.py", line 685, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/data/cogs/Downloader/lib/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'```

**Comment by PhasecoreX** [comment]
For anyone seeing this in the future, use the `full` tag, as it has `ffmpeg` installed already.
