### ISSUE TITLE
Audio cog, failed import apsw

### ISSUE THREAD

**Issue by agilly1989** [PhasecoreX/docker-red-discordbot#26]
Container: full
Command: [p]load audio
Traceback:
`Exception during import of package
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 155, in _load
    spec = await bot._cog_mgr.find_cog(name)
  File "/data/venv/lib/python3.8/site-packages/redbot/core/cog_manager.py", line 292, in find_cog
    return await self._find_core_cog(name)
  File "/data/venv/lib/python3.8/site-packages/redbot/core/cog_manager.py", line 260, in _find_core_cog
    mod = import_module(real_name, package=package)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/__init__.py", line 3, in <module>
    from .core import Audio
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/core/__init__.py", line 19, in <module>
    from . import abc, cog_utils, commands, events, tasks, utilities
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/core/abc.py", line 18, in <module>
    from redbot.core.utils.dbtools import APSWConnectionWrapper
  File "/data/venv/lib/python3.8/site-packages/redbot/core/utils/dbtools.py", line 7, in <module>
    import apsw
ImportError: /data/venv/lib/python3.8/site-packages/apsw.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object`

From what I can see, it can't import apsw. I have tried to [p]pipinstall it and to activate the venv manually to install it with no luck.

Not too sure if this is a "you" problem or if it's a "cogs.red" problem, so I thought I would ask here first

**Comment by PhasecoreX** [comment]
I'm worried that me fixing (or rather, bypassing) #25 was just kicking the can down the road for this execution issue. When you get the chance, can you have the container started, then enter the container with:
```
sudo docker exec -t -i <your_container_name> bash
```
Now that you're in the container, run this:
```
mount | grep /data
```
and this:
```
ls -l /data/venv/lib/python3.8/site-packages/*.so
```
Let me know what each one outputs

**Comment by PhasecoreX** [comment]
Yup there it is. Since that first command has `noexec` in it, nothing from that partition (that the `/data` volume is coming from) can be executed. For Audio to work, it needs to be able to execute that shared object that apsw provides.

I'm not sure how your `/dev/sdc1` partition is configured, but usually it's with the `/etc/fstab` file. You need to remove `noexec` from the mount options or else audio will never work. Or, have the `/data` mount come from some other location that allows executing.

Also, I'm probably going to revert the change in #25 and put a check in place looking for this `noexec` on the mount. No sense in starting the bot if it isn't going to work completely, and it'll be back to the "recommended" way to start the bot that the RedBot docs suggest.

**Comment by agilly1989** [comment]
AH, let me check the permissions in OMV and I will let you know

**Comment by PhasecoreX** [comment]
Image has been updated, it now checks for `noexec` on the `/data` volume mount and refuses to start (and gives a hopefully helpful notification) if present.
