### ISSUE TITLE
Red boot looping 

### ISSUE THREAD

**Issue by RasenShurik3n** [PhasecoreX/docker-red-discordbot#39]
Using the full version, and was working flawlessly, then 1 week ago started giving me this error and boot looping

Timezone set to Europe/Athens

Starting with UID/GID: 1000/1000

Activating Python virtual environment...

Updating Red-DiscordBot...

Setting bot token...

Traceback (most recent call last):

  File "/data/venv/bin/redbot", line 5, in <module>

    from redbot.__main__ import main

  File "/data/venv/lib/python3.8/site-packages/redbot/__main__.py", line 30, in <module>

    from redbot.core.bot import Red, ExitCodes

  File "/data/venv/lib/python3.8/site-packages/redbot/core/__init__.py", line 4, in <module>

    from .config import Config

  File "/data/venv/lib/python3.8/site-packages/redbot/core/config.py", line 21, in <module>

    from .drivers import IdentifierData, get_driver, ConfigCategory, BaseDriver

  File "/data/venv/lib/python3.8/site-packages/redbot/core/drivers/__init__.py", line 4, in <module>

    from .. import data_manager

  File "/data/venv/lib/python3.8/site-packages/redbot/core/data_manager.py", line 12, in <module>

    from discord.utils import deprecated

ImportError: cannot import name 'deprecated' from 'discord.utils' (/data/venv/lib/python3.8/site-packages/discord/utils.py)

**Comment by PhasecoreX** [comment]
Weird, I cannot reproduce this. Can you try stopping the container, deleting the `/data/venv` folder, and then restarting the container? Also what hardware are you running on, and how are you running the container?
