### ISSUE TITLE
lavalink install fails

### ISSUE THREAD

**Issue by dafzor** [PhasecoreX/docker-red-discordbot#5]
When enabling the Audio cog the Lavalink.jar download fails.

Here is the log including issued commands starting with `>`
```
> [p]load audio
[2019-05-20 19:20:30] [INFO] red.audio.manager: Downloading Lavalink.jar...
> [p]llsetup external
> [p]llsetup external
[2019-05-20 19:23:56] [INFO] red.audio.manager: Downloading Lavalink.jar...
[2019-05-20 19:24:24] [ERROR] red.audio: Connecting to Lavalink server timed out, retrying...
[2019-05-20 19:24:25] [INFO] red.audio.manager: Downloading Lavalink.jar...
Task exception was never retrieved
future: <Task finished coro=<Audio.attempt_connect() done, defined at /data/venv/lib/python3.7/site-packages/redbot/cogs/audio/audio.py:123> exception=OSError(18, 'Invalid cross-device link')>
Traceback (most recent call last):
  File "/data/venv/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 136, in attempt_connect
    await self._manager.start()
  File "/data/venv/lib/python3.7/site-packages/redbot/cogs/audio/manager.py", line 62, in start
    await self.maybe_download_jar()
  File "/data/venv/lib/python3.7/site-packages/redbot/cogs/audio/manager.py", line 243, in maybe_download_jar
    await cls._download_jar()
  File "/data/venv/lib/python3.7/site-packages/redbot/cogs/audio/manager.py", line 216, in _download_jar
    pathlib.Path(path).replace(LAVALINK_JAR_FILE)
  File "/usr/local/lib/python3.7/pathlib.py", line 1321, in replace
    self._accessor.replace(self, target)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpgkgk1im6' -> '/data/cogs/Audio/Lavalink.jar'
```
setting environment variables `TMPDIR`, `TMP`, `TEMP` to `/data/tmp` doesn't seem to help.

**Comment by PhasecoreX** [comment]
I'll try and recreate this error in my environment, but for the time being, a workaround is to manually download the jar file from https://github.com/Cog-Creators/Lavalink-Jars/releases/latest and place it in `/data/cogs/Audio/Lavalink.jar` (wherever you have the /data folder mounted).

Since this is Docker, the file system that /tmp and /data use will be different, hence the error. The correct fix would be to update how Redbot does it's jar updating. Instead of `.replace`, something like a `shutil.move` should be used instead to support cross-device copying.

Odd that setting `TMPDIR` didn't fix it though, since python is supposed to honor that setting...

**Comment by dafzor** [comment]
It's my first time using docker so I may very well be doing something wrong. Regardless I've linked this to a [new issue](https://github.com/Cog-Creators/Red-DiscordBot/issues/2714) on red-discordbot. Thanks for confirming it.

**Comment by PhasecoreX** [comment]
Alright sorry it took a bit, but I implemented the `TMPDIR` that was mentioned in the linked issue and it seems to have fixed this issue. The auto builds will finish in the next half hour ([shameless plug for my UpdateNotify cog](https://github.com/PhasecoreX/PCXCogs)), then you can pull the updated image and see if lavalink downloads correctly. Thanks for pointing this out!
