### ISSUE TITLE
Bot connects to voice chat, gets track error and disconnects

### ISSUE THREAD

**Issue by DeadlyVirez** [PhasecoreX/docker-red-discordbot#56]
**Describe the bug**
The Bot starts up fine but as soon as a track from youtube is tried to be played the bot connects to the voice channel, reports a Track Error and disconnects again.
This has been tried with multiple tracks, as well as clearing the 'venv' folder and restarting the bot.

**Run command**
```
version: "3.2"
services:
  redbot:
    container_name: groovier_bot
    image: phasecorex/red-discordbot:full
    restart: unless-stopped
    volumes:
      - /home/XXXX/projects/redbot/:/data
    environment:
      - TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXX
      - PREFIX=.
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1008
      - EXTRA_ARGS=--debug
```

**Environment info:**
```

OS: Ubuntu 20.04.4 LTS x86_64
Kernel: 5.4.0
Uptime: 30 days, 20 hours, 6 mins
Packages: 843 (dpkg)
Shell: bash 5.0.17
Terminal: /dev/pts/0
CPU: Intel Xeon E5-2680 v3 (4) @ 1.999GHz
Memory: 516MiB / 8192MiB

```

**Additional context**
```
groovier_bot | [2022-08-11 22:14:07] [INFO] red.Audio.manager: Internal Lavalink server started. PID: 124
groovier_bot | [2022-08-11 22:14:07] [DEBUG] red.Audio.manager: Waiting for Lavalink server to be ready
groovier_bot | [2022-08-11 22:14:11] [DEBUG] red.Audio.manager: Seen first 'Started Launcher' line from internal Lavalink server. Waiting for the second one...
groovier_bot | [2022-08-11 22:14:13] [INFO] red.Audio.manager: Internal Lavalink server is ready to receive requests.
groovier_bot | [2022-08-11 22:14:13] [INFO] red.Audio.WS.LLNode: Lavalink WS connecting to ws://localhost:2333 with headers {'Authorization': 'youshallnotpass', 'User-Id': '880549066331787314', 'Num-Shards': '1', 'Client-Name': 'Red-Lavalink/0.9.3', 'Resume-Key': 'Red-Core-Audio-880549066331787314-docker'}
groovier_bot | [2022-08-11 22:14:14] [DEBUG] red.Audio.WS.LLNode: Creating Lavalink WS listener.
groovier_bot | [2022-08-11 22:14:14] [DEBUG] red.Audio.WS.LLNode: Changing node state: CONNECTING -> READY
groovier_bot | [2022-08-11 22:14:14] [DEBUG] red.Audio.WS.LLNode: Sending data to Lavalink node: {'op': 'configureResuming', 'key': 'Red-Core-Audio-880549066331787314-docker', 'timeout': 60}
groovier_bot | [2022-08-11 22:14:14] [DEBUG] red.Audio.WS.LLNode: Node Resuming has been configured.
groovier_bot | [2022-08-11 22:14:14] [DEBUG] red.Audio.WS.RLL: Received node state update: CONNECTING -> READY
groovier_bot | [2022-08-11 22:14:14] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'playingPlayers': 0, 'op': 'stats', 'memory': {'reservable': 2147483648, 'used': 33408464, 'free': 218249776, 'allocated': 251658240}, 'players': 0, 'cpu': {'cores': 4, 'systemLoad': 0, 'lavalinkLoad': 0.2648221343873518}, 'uptime': 5721}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.RLL: Player <Player: state=CREATED, connected=True, guild='XXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=False, paused=False, volume=100, queue_size=0, current=None, position=0, length=0, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> changing state: CREATED -> READY
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: Sending data to Lavalink node: {'op': 'volume', 'guildId': '180816944570695680', 'volume': 70}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.cogs.Audio.api.AudioAPIInterface: Updating Local Database with 'https://www.youtube.com/watch?v=Bu8bH2P37kY'
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.core.RLL: Assigned current track for player: <Player: state=READY, connected=True, guild='XXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>>.
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: Sending data to Lavalink node: {'op': 'play', 'guildId': '180816944570695680', 'track': 'QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', 'noReplace': False, 'startTime': '0', 'pause': False}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'event', 'type': 'TrackStartEvent', 'track': 'QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.cogs.Audio.cog.Events.lavalink: Received a new lavalink event for 180816944570695680: LavalinkEvents.TRACK_START: 'QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA=='
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.core.RLL: Received player event for player: <Player: state=READY, connected=True, guild='XXXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - <LavalinkEvents.TRACK_START: 'TrackStartEvent'> - 'QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA=='.
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'playerUpdate', 'state': {'connected': False, 'position': 0, 'time': 1660248884317}, 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'playerUpdate', 'state': {'connected': False, 'position': 0, 'time': 1660248884327}, 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.core.RLL: Updated player position for player: <Player: state=READY, connected=True, guild='XXXXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - 0s.
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.core.RLL: Updated player position for player: <Player: state=READY, connected=True, guild='XXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - 0s.
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: Received Discord WS voice response for guild: 180816944570695680, {'t': 'VOICE_STATE_UPDATE', 's': 4, 'op': 0, 'd': {'member': {'user': {'username': 'Groovier Bot', 'public_flags': 0, 'id': '880549066331787314', 'discriminator': '6134', 'bot': True, 'avatar': '4d10a84334890300d097a5f9c6ebd020'}, 'roles': ['882331488455118848'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2021-08-31T19:35:21.350000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'avatar': None}, 'user_id': '880549066331787314', 'suppress': False, 'session_id': '5e5d189c3295af87e1d77ecc8fa4096f', 'self_video': False, 'self_mute': False, 'self_deaf': True, 'request_to_speak_timestamp': None, 'mute': False, 'guild_id': '180816944570695680', 'deaf': False, 'channel_id': '230394468233117697'}}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.cogs.Audio.api.AudioAPIInterface: Running database writes for 1007381575706615878 (DeadlyVirez#6990)
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.cogs.Audio.api.AudioAPIInterface: Completed database writes for 1007381575706615878 (DeadlyVirez#6990)
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: Received Discord WS voice response for guild: 180816944570695680, {'t': 'VOICE_SERVER_UPDATE', 's': 7, 'op': 0, 'd': {'token': '6b2faffc7baad1c9', 'guild_id': '180816944570695680', 'endpoint': 'rotterdam2708.discord.media:443'}}
groovier_bot | [2022-08-11 22:14:44] [DEBUG] red.Audio.WS.LLNode: Sending data to Lavalink node: {'op': 'voiceUpdate', 'guildId': '180816944570695680', 'sessionId': '5e5d189c3295af87e1d77ecc8fa4096f', 'event': {'token': '6b2faffc7baad1c9', 'guild_id': '180816944570695680', 'endpoint': 'rotterdam2708.discord.media:443'}}
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'playerUpdate', 'state': {'connected': False, 'position': 0, 'time': 1660248885317}, 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.core.RLL: Updated player position for player: <Player: state=READY, connected=True, guild='XXXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - 0s.
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'playerUpdate', 'state': {'connected': True, 'position': 0, 'time': 1660248885355}, 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.core.RLL: Updated player position for player: <Player: state=READY, connected=True, guild='XXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - 0s.
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'exception': {'severity': 'FAULT', 'cause': 'java.lang.IllegalStateException: No match found', 'message': 'Something broke when playing the track.'}, 'op': 'event', 'type': 'TrackExceptionEvent', 'track': 'QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', 'error': 'Something broke when playing the track.', 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.cogs.Audio.cog.Events.lavalink: Received a new lavalink event for 180816944570695680: LavalinkEvents.TRACK_EXCEPTION: {'message': 'Something broke when playing the track.', 'cause': 'java.lang.IllegalStateException: No match found', 'severity': <ExceptionSeverity.FAULT: 'FAULT'>}
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.core.RLL: Received player event for player: <Player: state=READY, connected=True, guild='XXXXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - <LavalinkEvents.TRACK_EXCEPTION: 'TrackExceptionEvent'> - {'message': 'Something broke when playing the track.', 'cause': 'java.lang.IllegalStateException: No match found', 'severity': <ExceptionSeverity.FAULT: 'FAULT'>}.
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'event', 'reason': 'LOAD_FAILED', 'type': 'TrackEndEvent', 'track': 'QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.cogs.Audio.cog.Events.lavalink: Received a new lavalink event for 180816944570695680: LavalinkEvents.TRACK_END: <TrackEndReason.LOAD_FAILED: 'LOAD_FAILED'>
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.core.RLL: Received player event for player: <Player: state=READY, connected=True, guild='XXXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=True, paused=False, volume=70, queue_size=0, current=<Track: track_identifier='QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==', author='Tache Memes', length=6000, is_stream=False, uri='https://www.youtube.com/watch?v=Bu8bH2P37kY', title='Hello, how are you? I am under the water'>, position=0, length=6000, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - <LavalinkEvents.TRACK_END: 'TrackEndEvent'> - <TrackEndReason.LOAD_FAILED: 'LOAD_FAILED'>.
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.Audio.WS.LLNode: Sending data to Lavalink node: {'op': 'stop', 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.cogs.Audio.cog.Events.lavalink: Received a new lavalink event for 180816944570695680: LavalinkEvents.QUEUE_END: None
groovier_bot | [2022-08-11 22:14:45] [DEBUG] red.core.RLL: Received player event for player: <Player: state=READY, connected=True, guild='XXXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=False, paused=False, volume=70, queue_size=0, current=None, position=0, length=0, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> - <LavalinkEvents.QUEUE_END: 'QueueEndEvent'> - None.
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.Audio.WS.RLL: Player <Player: state=READY, connected=False, guild='XXXXXXX' (180816944570695680), channel='Voice Chat' (230394468233117697), playing=False, paused=False, volume=70, queue_size=0, current=None, position=0, length=0, node=<Node: state=READY, host=localhost, port=2333, password=***************, resume_key=Red-Core-Audio-880549066331787314-docker, shards=1, user=880549066331787314, stats=<NodeStats: uptime=5721, players=0, playing_players=0, memory_free=218249776, memory_used=33408464, cpu_cores=4, system_load=0, lavalink_load=0.2648221343873518>>> changing state: READY -> DISCONNECTING
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.Audio.WS.LLNode: Sending data to Lavalink node: {'op': 'destroy', 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.core.RLL: Closed REST session.
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'event', 'reason': '', 'code': 1000, 'byRemote': False, 'type': 'WebSocketClosedEvent', 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.Audio.WS.LLNode: [NODE] | Received known op: {'op': 'playerUpdate', 'state': {'connected': False, 'time': 1660248888306}, 'guildId': '180816944570695680'}
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.core.RLL: Got an event for a guild that we have no player for. This may be because of a forced voice channel disconnect.
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.core.RLL: Got a player update for a guild that we have no player for. This may be because of a forced voice channel disconnect.
groovier_bot | [2022-08-11 22:14:48] [DEBUG] red.Audio.WS.LLNode: Received Discord WS voice response for guild: 180816944570695680, {'t': 'VOICE_STATE_UPDATE', 's': 10, 'op': 0, 'd': {'member': {'user': {'username': 'Groovier Bot', 'public_flags': 0, 'id': '880549066331787314', 'discriminator': '6134', 'bot': True, 'avatar': '4d10a84334890300d097a5f9c6ebd020'}, 'roles': ['882331488455118848'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2021-08-31T19:35:21.350000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'avatar': None}, 'user_id': '880549066331787314', 'suppress': False, 'session_id': '5e5d189c3295af87e1d77ecc8fa4096f', 'self_video': False, 'self_mute': False, 'self_deaf': True, 'request_to_speak_timestamp': None, 'mute': False, 'guild_id': '180816944570695680', 'deaf': False, 'channel_id': None}}
groovier_bot | [2022-08-11 22:14:48] [INFO] red.Audio.WS.RLL: Received voice disconnect from discord, removing player.

```

**Comment by DeadlyVirez** [comment]
additionally here is the lavalink log I found:

```
2022-08-11 22:14:44.288  INFO 124 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "180816944570695680", "track": "QAAAjQIAKEhlbGxvLCBob3cgYXJlIHlvdT8gSSBhbSB1bmRlciB0aGUgd2F0ZXIAC1RhY2hlIE1lbWVzAAAAAAAAF3AAC0J1OGJIMlAzN2tZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QnU4YkgyUDM3a1kAB3lvdXR1YmUAAAAAAAAAAA==", "noReplace": false, "startTime": "0", "pause": false}
2022-08-11 22:14:44.803  INFO 124 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "180816944570695680", "sessionId": "5e5d189c3295af87e1d77ecc8fa4096f", "event": {"token": "6b2faffc7baad1c9", "guild_id": "180816944570695680", "endpoint": "rotterdam2708.discord.media:443"}}
2022-08-11 22:14:45.661 ERROR 124 --- [lava-daemon-pool-playback-1-thread-1] .s.d.l.s.y.YoutubeSignatureCipherManager : Problematic YouTube player script /s/player/324f67b9/player_ias.vflset/de_DE/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script6706757298841271287.js.
2022-08-11 22:14:45.684 ERROR 124 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of Bu8bH2P37kY

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.98-devoxin
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0
  java.vendor: Debian
  java.version: 11.0.16
  java.runtime.version: 11.0.16+8-post-Debian-1deb11u1
  java.vm.version: 11.0.16+8-post-Debian-1deb11u1
Caused by: java.lang.IllegalStateException: No match found
        at java.base/java.util.regex.Matcher.group(Matcher.java:645) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:243) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:160) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:197) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:46) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:34) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[walkyst-lavaplayer-85f4877.jar!/:na]
        ... 4 common frames omitted
```

**Comment by DeadlyVirez** [comment]
I tried Spotify and Soundcloud in the meantime.

It seems like Spotify is also affected but not Soundcloud

**Comment by drixtol** [comment]
Chiming in to say im having the same issue. I can pull the logs if needed.

**Comment by dmizelle** [comment]
Ran into this as well. Grabbed the latest pre-release from https://github.com/Cog-Creators/Lavalink-Jars/releases and dropped it into `$DATA_DIR/cogs/Audio/Lavalink.jar`. The bot should auto download it, but latest stable was broken.

**Comment by DeadlyVirez** [comment]
can confirm. This works!

There is an information on the release changelog, which I didn't think applied here:
![grafik](https://user-images.githubusercontent.com/24830874/184269734-bb1026e4-8a7e-4cd6-a5df-06e2f07d7e90.png)

[https://docs.discord.red/en/stable/changelog_3_4_0.html#redbot-3-4-17-2022-06-07](url)

**Comment by PhasecoreX** [comment]
No, that shouldn't apply... we're just letting the Audio cog manage downloading and running the jar file itself, just like if you were to run the bot locally with no external Lavalink. Maybe there's some bug with the current version of the jar, that the prerelease fixed, but the Audio cog doesn't know about and thus won't download.

**Comment by PhasecoreX** [comment]
Yeah, it's something with the jar: https://github.com/Cog-Creators/Red-DiscordBot/issues/5819

For the time being, you can manually get the prelelease, otherwise they will push a fix soon.

**Comment by PhasecoreX** [comment]
3.4.18 was released, do a `[p]restart` to update to it, audio should be fixed
