### ISSUE TITLE
Container does not stop when bot crashes

### ISSUE THREAD

**Issue by Chiggy-Playz** [PhasecoreX/docker-red-discordbot#64]
**Describe the bug**
The bot crashed due to a network error and the container kept running. Bot had exited on 23rd march, I noticed the bot was down on 26th and the container's uptime was 10 days.

Traceback from the logs:
```py
[2023-03-23 21:28:19] [CRITICAL] red.main: The main bot task didn't handle an exception and has crashed
Traceback (most recent call last):
  File "/data/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/data/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/data/venv/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "uvloop/loop.pyx", line 1514, in getaddrinfo
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.9/site-packages/redbot/__main__.py", line 477, in red_exception_handler
    red_task.result()
  File "/data/venv/lib/python3.9/site-packages/redbot/__main__.py", line 389, in run_bot
    await red.start(token, bot=True, cli_flags=cli_flags)
  File "/data/venv/lib/python3.9/site-packages/redbot/core/bot.py", line 1202, in start
    return await super().start(*args, **kwargs)
  File "/data/venv/lib/python3.9/site-packages/discord/client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "/data/venv/lib/python3.9/site-packages/discord/client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/data/venv/lib/python3.9/site-packages/discord/http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/data/venv/lib/python3.9/site-packages/discord/http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/data/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/data/venv/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/data/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/data/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/data/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
[2023-03-23 21:28:19] [WARNING] red.main: Attempting to die as gracefully as possible...
[2023-03-23 21:28:19] [INFO] red.main: Shutting down from unhandled exception
[2023-03-26 19:49:52] [INFO] red.main: Signals.SIGTERM received. Quitting...
[2023-03-26 19:49:52] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2023-03-26 19:49:52] [INFO] red.main: Please wait, cleaning up a bit more
```

**Run command**
```yml
# Docker Compose
  redbot:
      container_name: redbot
      image: phasecorex/red-discordbot
      restart: unless-stopped
      volumes:
        - /red:/data
      environment:
        - TOKEN=token
        - PREFIX=.
        - TZ=Asia/Calcutta
        - PUID=1000
```

**Environment info:**
Debian 11.4

**Additional context**
None

**Comment by PhasecoreX** [comment]
Based on your logs, it seems that the bot itself got stuck in the "Please wait, cleaning up a bit more" part of its shutdown process. The container only starts the bot, and when it exits, can restart it depending on how you launched the container (the restart policy). But to the container, the bot is still running, so nothing will happen. Seems like an issue with redbot itself.

You can use my Heartbeat cog to monitor your bots uptime, I think there might be another cog that does the same thing but in reverse (mine posts out to an external service, the other runs a web server and expects the be queried for information). It won't solve this issue, but you will know within minutes if something brings your bot down.

**Comment by Chiggy-Playz** [comment]
Welp :( 
I understand the issue but don't want to setup a web server for this. Is it possible to setup a shell script inside the docker container that uses curl for the heartbeat and then restart the container if heartbeat fails?

**Comment by PhasecoreX** [comment]
You wouldn't have to set up a web server with my Heartbeat cog, you just make an account at a service like https://healthchecks.io/ and then point the Heartbeat cog at the URL it provides. Then when Healthchecks doesn't get a ping from the cog/bot after a minute or whatever you set as the timeout, it'll notify you. I have mine set up to ping every minute, with a grace period of one minute.

I don't think redbot has anything running inside of it that could respond to docker health check pings. So there's nothing for a curl to call out to, and thus no way to detect if redbot is stuck.

Another solution would be running another bot that watches for the first bot if it ever disconnects. But that would be running a second bot which is a lot of overhead... But if you're already running a second one then not so bad.

**Comment by Chiggy-Playz** [comment]
The healthchecks solution is a good one, but manual (Me having to restart the container myself :p), hence I was asking for a script inside the container itself to restart the container if heartbeat fail. I suppose I can just use healthchecks if any further automation is not possible.

**Comment by PhasecoreX** [comment]
Yeah, I can't really think of anything more that can be done to make it more automatic... It all hinges on the fact that redbot never actually exits. If it did, we're already covered. The container would exit, restart policy would restart it. If redbot exits with error code 26, that's its way of saying it wants to restart from the `[p]restart` command, so the container handles that as well (regardless of container restart policy).
