### ISSUE TITLE
Permissions issues with latest version

### ISSUE THREAD

**Issue by BGannon2** [PhasecoreX/docker-red-discordbot#73]
PermissionError Permission denied when running docker-compose up at the setting bot token step on latest. Watchtower auto updated the container yesterday and it seems to have come with the latest version.

Running with `sudo docker-compose up -d`

```Setting bot token...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/root/.local/share/Red-DiscordBot/data/docker/core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/venv/lib/python3.11/site-packages/redbot/__main__.py", line 562, in <module>
    main()
  File "/data/venv/lib/python3.11/site-packages/redbot/__main__.py", line 483, in main
    early_exit_runner(cli_flags, edit_instance)
  File "/data/venv/lib/python3.11/site-packages/redbot/__main__.py", line 284, in early_exit_runner
    red = Red(cli_flags=cli_flags, description="Red V3", dm_help=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 107, in __init__
    self._config = Config.get_core_conf(force_registration=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/redbot/core/config.py", line 742, in get_core_conf
    return cls.get_conf(
           ^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/redbot/core/config.py", line 717, in get_conf
    driver = get_driver(cog_name, uuid, allow_old=allow_old)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/redbot/core/_drivers/__init__.py", line 127, in get_driver
    return driver_cls(cog_name, identifier, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/redbot/core/_drivers/json.py", line 70, in __init__
    self.data_path = data_manager.core_data_path()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/redbot/core/data_manager.py", line 186, in core_data_path
    core_path.mkdir(exist_ok=True, parents=True)
  File "/usr/local/lib/python3.11/pathlib.py", line 1125, in mkdir
    if not exist_ok or not self.is_dir():
                           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1250, in is_dir
    return S_ISDIR(self.stat().st_mode)
                   ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/root/.local/share/Red-DiscordBot/data/docker/core'
```

I have deleted the venv directory, got a new token from discord and recreated the container with the same issue.
My docker-compose file looks like this:
``` redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - ./redbot:/data
    environment:
      - TOKEN=${DISCORD_BOT_TOKEN}
      - PREFIX=.
      - TZ=America/New_York
      - PUID=1000

**Comment by PhasecoreX** [comment]
I will look into this when I get time tomorrow. At first glance though, I am confused on why Red-DiscordBot is trying to write to that `/root` directory. That would only happen if you were running it as root, but I see you're using ID 1000. Additionally, it should be saving that token info to `/data/core`, not in the `/root` directory.

Can you show me what is in your `/data/config.json` file?

**Comment by BGannon2** [comment]
```$ cat config.json
{
    "docker": {
        "DATA_PATH": "/root/.local/share/Red-DiscordBot/data/docker",
        "COG_PATH_APPEND": "cogs",
        "CORE_PATH_APPEND": "core",
        "STORAGE_TYPE": "JSON",
        "STORAGE_DETAILS": {}
    }
```

**Comment by PhasecoreX** [comment]
Delete the `/data/config.json` file and then start the container again.

If that doesn't work, change the `"DATA_PATH": "/root/.local/share/Red-DiscordBot/data/docker",` line to just say `"DATA_PATH": "/data",`

**Comment by BGannon2** [comment]
This resolved my issue, thank you.

**Comment by desentizised** [comment]
This (just not using the config.json) resolved my issue as well. 

![image](https://github.com/PhasecoreX/docker-red-discordbot/assets/75106673/aee24126-a006-4fa5-9eb0-3ad2fc3fff43)
