### ISSUE TITLE
Track Error - Something broke when playing the track (YouTube)

### ISSUE THREAD

**Issue by d4rkd3n1337** [PhasecoreX/docker-red-discordbot#93]
Hello! After attempt start playback from youtube I get next errors. 
link or by name - it doesn't matter
`Track Error
Something broke when playing the track.`
I trying to create a 'new' instance (contaner) and new bot in discord for testing, but it didn't change the situation.
OS: Debian 12
Docker version: 20.10.24+dfsg1
Docker Compose version: v2.27.0
RedBot version is 100% last

`version: "3.2"
services:
  redbot:
    container_name: redbot-test
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - /opt/ydk-docker/redbot-test:/data
    environment:
      - TOKEN=token_here
      - PREFIX=%
      - TZ=Europe/Moscow
      - PUID=1000`
I saw the latest lawsuit about Debian 12 and JDK17, and waited for it, but nothing changed after the update. 
Is this a problem with RedBot itself or is something broken in the container?

P.S. Sorry for my bad english

**Comment by rmartin16** [comment]
FWIW, this is the lavalink log for me....yt is returning a 403:
```java
2024-07-10 00:34:21.540  INFO 337 --- [XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "718975344350068796", "track": "QAAAcAIADUxvdmUgV2Fsa3MgSW4ACVZhbiBIYWxlbgAAAAAABL7YAAs4cWNRMzRpVHN3WQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PThxY1EzNGlUc3dZAAd5b3V0dWJlAAAAAAAAAAA=", "noReplace": false, "startTime": "0", "pause": false}
2024-07-10 00:34:22.525 ERROR 337 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 8qcQ34iTswY

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT
  os.arch: amd64
  os.name: Linux
  os.version: 6.9.3-76060903-generic
  java.vendor: Debian
  java.version: 17.0.11
  java.runtime.version: 17.0.11+9-Debian-1deb12u1
  java.vm.version: 17.0.11+9-Debian-1deb12u1
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:na]
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:83) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStaticWithRetry(YoutubeAudioTrack.java:65) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:52) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT.jar!/:na]
	... 4 common frames omitted
```

The redbot team has a [message](https://discord.com/channels/133049272517001216/387398816317440000/1260591417667878932) in their discord about this KI.

**Comment by d4rkd3n1337** [comment]
Thanks you very much for your fast reply! So, waiting to update by redbot's team

**Comment by PhasecoreX** [comment]
Yeah, it's up to the Red/Lavalink devs to fix this, and more than likely this issue will continue to come up as YouTube cracks down on 3rd party players.
